/***********************************************************************/
/*                                                                     */
/*  FILE        :typedefine.h                                          */
/*  DATE        :Fri, May 22, 2020                                     */
/*  DESCRIPTION :Aliases of Integer Type                               */
/*  CPU TYPE    :H8/3694F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  


typedef   signed char 	_S1;
typedef unsigned char 	_U1;
typedef   signed short 	_S2;
typedef unsigned short 	_U2;
typedef   signed long 	_S4;
typedef unsigned long 	_U4;
